services:
  rabbitmq:
    image: rabbitmq:4.0.4-management-alpine
    container_name: destaxa-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - destaxa-network

  destaxa-api:
    build:
      context: ./destaxa-api/
      dockerfile: ./.docker/Dockerfile
    container_name: destaxa-api
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - destaxa-autorizador
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    networks:
      - destaxa-network

  destaxa-autorizador:
    build:
      context: ./destaxa-autorizador
      dockerfile: ./.docker/Dockerfile
    container_name: destaxa-autorizador
    ports:
      - "8081:8080"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    networks:
      - destaxa-network

volumes:
  rabbitmq_data: {}

networks:
  destaxa-network:
    driver: bridge