spring:
  application:
    name: destaxa-autorizador
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      authorization-queue:
        queue-name: ${AUTORIZACAO_QUEUE_NAME:autorizacao}
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          multiplier: 2.0
          max-interval: 10000
    template:
      default-receive-queue: ${AUTORIZACAO_RESPOSTA_QUEUE_NAME:autorizacao_resposta}
      retry:
        enabled: true
        max-attempts: 3
        initial-interval: 1000
        multiplier: 2.0
        max-interval: 10000

jpos:
  packager:
    path: /packager.xml

management:
  endpoints:
    web:
      exposure:
        include: '*'